---
on:
- push
- pull_request
name: ci

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.9.0

      - name: install dependencies
        run: pnpm i

      - name: build typescript
        run: pnpm run build


  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.9.0

      - name: install dependencies
        run: pnpm i

      - name: lint typescript
        run: pnpm run lint


#  test:
#    name: test
#    runs-on: ubuntu-20.04
#    steps:
#      - name: checkout code
#        uses: actions/checkout@v2
#
#      - name: setup node
#        uses: actions/setup-node@v1
#        with:
#          node-version: "12"
#
#      - name: Setup pnpm
#        uses: pnpm/action-setup@v1.2.1
#        with:
#          version: 5.9.0
#
#      - name: install dependencies
#        run: pnpm i
#
#      - name: test typescript
#        run: pnpm test
